services:
  api:
    build:
      context: ./vibez-api
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./protos:/protos

    develop:
      watch:
        - action: sync
          path: ./vibez-api
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./vibez-api/package.json

    depends_on:
      - grpc

  grpc:
    build: ./vibez-backend
    container_name: grpc
    ports:
      - "50051:50051"
    volumes:
      - ./protos:/protos